<?xml version= "1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE temporada [
<!ELEMENT temporada (jornada*)>
    <!ATTLIST temporada año CDATA #REQUIRED>
    <!ELEMENT jornada (partido*)>
        <!ATTLIST jornada numero CDATA #REQUIRED>
        <!ELEMENT partido (fecha,estadio,local,visitante,resultado)>
            <!ATTLIST partido numero CDATA #REQUIRED>
            <!ELEMENT fecha (#PCDATA)>
            <!ELEMENT estadio (#PCDATA)>
                <!ATTLIST estadio espectadores CDATA #DEFAULT "0">
            <!ELEMENT local (#PCDATA)>
            <!ELEMENT visitante (#PCDATA)>
            <!ELEMENT resultado (#PCDATA)>
                <!ATTLIST resultado local CDATA #REQUIRED>
                <!ATTLIST resultado visitante CDATA #REQUIRED>
]>

<temporada año="2000">
    <jornada numero="1">
        <partido numero="1">
            <fecha>2000-02-02</fecha>
            <estadio espectadores="49000">Landsdown
            Road</estadio>
            <local>Irlanda</local>
            <visitante>Inglaterra</visitante>
            <resultado local="17" visitante="6"/>
        </partido>
    </jornada>
    <jornada numero="2">
    </jornada>
</temporada>
