<?xml version='1.0'?>
<!DOCTYPE librococina [
<!ELEMENT librococina (id+,ingrediente+)>
<!ELEMENT id (#PCDATA)>
<!ATTLIST id receta ID #REQUIRED>
<!ELEMENT ingrediente (#PCDATA)>
<!ATTLIST ingrediente ref IDREFS #REQUIRED>
]>
<librococina>
    <id receta="rec_1"> Mousse de chocolate</id>
    <id receta="rec_2"> Fondue saboyana</id>
    <id receta="rec_3"> Fondue de chocolate</id>
    <ingrediente ref="rec_1 rec_3"> chocolate </ingrediente>
    <ingrediente ref="rec_2"> Comt√© </ingrediente>
</librococina>