<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE noticias [
<!ELEMENT noticias (noticia)*>
<!ELEMENT noticia (titulo,autor,url,texto,foto)>
<!ATTLIST noticia dia CDATA #REQUIRED>
<!ATTLIST noticia mes CDATA #REQUIRED>
<!ATTLIST noticia anyo CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ATTLIST url direccion CDATA #REQUIRED>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
]>

<noticias>
    <noticia dia="22" mes="10" anyo="2005">
        <titulo> Nuevo Servidor WEB </titulo>
        <autor> Antonio Barco </autor >
        <url direccion=""> http://www.abc.es </url>
        <texto> En los últimos días ha visto la luz un nuevo
        servidor Web en la Comunidad Valenciana </texto >
        <foto>http://www.abc.es/122.jpg</foto>
    </noticia>
    <noticia dia="12" mes="11" anyo="2005">
        <titulo> Premio de Biología </titulo>
        <autor> Pilar Garcia</autor >
        <url direccion=""> http://www.abc.es </url>
        <texto> Los alumnos del Colegio Europa ganan el premio de
        Biología de la Comunidad Autónoma de Andalucía </texto >
        <foto>http://www.abc.es/123.jpg</foto>
    </noticia>
</noticias>